### ISSUE TITLE
Question about training epochs and training logs

### ISSUE THREAD

**Issue by pengzhiliang** [facebookresearch/xcit#1]
Hello, thank u for another simple but effective work!

In your paper, the training epochs is setting as :
```text
We train our model for 400 epochs with the AdamW optimizer [45] using a cosine learning rate decay.
````
but the default epochs in your code is setting as **300 epochs** and doesn't be changed in command line. 

So, I'm confused about it.

By the way, could you publish your training logs?

**Comment by aelnouby** [comment]
Thanks for your question. We indeed use 400 epochs by default. I have added a commit to reflect that (https://github.com/facebookresearch/xcit/commit/177cefa8b4774255eddc3eb81f01e0ca3d1103b0)

**Comment by pengzhiliang** [comment]
OK, thank u~
