### ISSUE TITLE
An Issue !

### ISSUE THREAD

**Issue by tanujdhiman** [facebookresearch/xcit#12]
This particular repository is for only like detection model i.e COCO. Or can we add more models into this ?

Thanks

**Comment by aelnouby** [comment]
I am sorry, I am not sure I understood your question. Do you mean can the detection model be used for other datasets other than COCO ? 

If this is your question, the answer should be yes. You will just have the follow the mmdetection guide for additional datasets.

**Comment by aelnouby** [comment]
Please re-open the issue if you have another question.

**Comment by tanujdhiman** [comment]
I want to ask basically can we add more models in this repository That's my question ?

**Comment by aelnouby** [comment]
If you train a model with XCiT backbone and you think it might be useful for the community to have access to that model definition and weights you can add a pull request.

**Comment by tanujdhiman** [comment]
Okay sure !
Thanks
