### ISSUE TITLE
segmentation readme pip instruction error?

### ISSUE THREAD

**Issue by mellorjc** [facebookresearch/xcit#14]
In

https://github.com/facebookresearch/xcit/blob/master/semantic_segmentation/README.md

should the line 
```
pip install mmcv-full==1.3.0 mmseg==0.11.0
```

instead be 

```
pip install mmcv-full==1.3.0 mmsegmentation==0.11.0
```

?

mmseg appears to be a library for segmenting chinese characters. https://pypi.org/project/mmseg/

**Comment by aelnouby** [comment]
Thanks for flagging this. It is should be fixed now (https://github.com/facebookresearch/xcit/commit/3e9549fae0eccc6f45fd9e6f81cb62201f0998ca)
