### ISSUE TITLE
Fine-tuning configurations

### ISSUE THREAD

**Issue by amoeba04** [facebookresearch/xcit#15]
Thank you for a great work.
I'm trying to reproduce transfer learning results, but I'm not sure about the fine-tuning configuration.
I read the issue below, but is it all (just smaller lr=5e-5 for classification)?
https://github.com/facebookresearch/xcit/issues/9#issuecomment-868494866

Would you inform me if there should be additional changes?

**Comment by aelnouby** [comment]
Thanks for your question. For the transfer learning experiments, we mostly follow the DeiT hyperparams as detailed in this [thread](https://github.com/facebookresearch/deit/issues/45#issuecomment-765213622).

Please let me know if you have more questions.
