### ISSUE TITLE
detectron2 integration?

### ISSUE THREAD

**Issue by lucasjinreal** [facebookresearch/xcit#16]
why not using detectron2 replicate some of those exp result in detection, since this is a work from FAIR.

**Comment by aelnouby** [comment]
Thanks for your question. We have used mmdetection to achieve most fair comparison with Swin and PVT and eliminate any factors that can impact the performance other than the method itself. 

Detectron2 Integration is certainly included in our future plans. I will post on this thread once we have any updates concerning D2 integration.
