### ISSUE TITLE
Training on Single GPU 

### ISSUE THREAD

**Issue by trathpai** [facebookresearch/xcit#17]
Thanks for the exciting work.

I am trying to finetune  on my classification (imagenet) like dataset on 1 GPU using following command.

`python -m torch.distributed.launch --nproc_per_node=1 --use_env main.py --model xcit_nano_12_p16 --batch-size 16 --drop-path 0.05 --output_dir experiments/xcit_nano_12_p16/ --epochs 30 --pretrained /mnt/hdd1/Projects/XCiT/xcit_nano_12_p16_224.pth`

But it fails with following error:
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [16, 1, 128]], which is output 0 of SliceBackward, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

what could be done to resolve this? I am new to distributed training .

**Comment by dwhite54** [comment]
~~I'm having the same problem training with multiple GPUs and the same model. After enabling anomaly detection (`torch.autograd.set_detect_anomaly(True)`) I'm pointed to the [timm.utils.cuda.loss_scaler](https://github.com/rwightman/pytorch-image-models/blob/bd5694667625d510e3aa89e95397de97d0e7efe9/timm/utils/cuda.py ) call of torch.cuda.amp.GradScaler.scale. Notably, the [documentation](https://pytorch.org/docs/stable/amp.html#torch.cuda.amp.GradScaler) states~~

> unscale_() should only be called once per optimizer per step() call, and only after all gradients for that optimizer’s assigned parameters have been accumulated. Calling unscale_() twice for a given optimizer between each step() triggers a RuntimeError.

~~I'm pretty inexperienced with the inner details of the optimizer, but this seems like a lead.~~

Edit: see below

**Comment by dwhite54** [comment]
This issue is reproduced for me using the same model with patch size 8, but not using tiny. It seems to be related to the "nano" models.

**Comment by dwhite54** [comment]
I found [the culprit](https://github.com/facebookresearch/xcit/blob/82f5291f412604970c39a912586e008ec009cdca/xcit.py#L209) (I was way off before). 
A workaround is to set `tokens_norm=True` ([here](https://github.com/facebookresearch/xcit/blob/82f5291f412604970c39a912586e008ec009cdca/xcit.py#L415) for example). Going by the comments, this will hurt your performance if you're just doing inference with a pretrained xcit_nano.

**Comment by trathpai** [comment]
> I found [the culprit](https://github.com/facebookresearch/xcit/blob/82f5291f412604970c39a912586e008ec009cdca/xcit.py#L209) (I was way off before).
> A workaround is to set `tokens_norm=True` ([here](https://github.com/facebookresearch/xcit/blob/82f5291f412604970c39a912586e008ec009cdca/xcit.py#L415) for example). Going by the comments, this will hurt your performance if you're just doing inference with a pretrained xcit_nano.

Thanks a lot . I will check it and update accordingly.

**Comment by trathpai** [comment]
Solution by @dwhite54 above works , so closing.
