### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv_custom'

### ISSUE THREAD

**Issue by ifding** [facebookresearch/xcit#3]
Thank you for publishing the great work! Please check the following error in xcit/detection/backbone/xcit.py file:

```
from mmcv_custom import load_checkpoint
ModuleNotFoundError: No module named 'mmcv_custom'
```

Probably you forgot to add this folder: https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/tree/master/mmcv_custom

Thanks again!

**Comment by aelnouby** [comment]
Thanks for spotting this problem ! It is suppsed to be fixed now (https://github.com/facebookresearch/xcit/commit/3bd7bf7f483aea18c63fbc242e4f27d3da486c17).
