### ISSUE TITLE
How to get FLOPs and model parameter

### ISSUE THREAD

**Issue by youngwanLEE** [facebookresearch/xcit#4]
Hi, 

I'm very impressed by your great work.

I wonder this repo provides model' FLOPs and parameters counter.

**Comment by aelnouby** [comment]
Thanks for your interest in our work. For the model params count, it is computed and printed during training or evaluation https://github.com/facebookresearch/xcit/blob/17dfb6e44c1de6062fc7770110f283f1c20fcf2f/main.py#L307. 
As for the FLOPS, you can use the [fvcore FLOP counter](https://github.com/facebookresearch/fvcore/blob/master/fvcore/nn/flop_count.py), it is the only third party package that I know of whose FLOPS counter is mostly correct for transformers.

Please let me know if you have any more questions.
