### ISSUE TITLE
How to visualize the attention map?

### ISSUE THREAD

**Issue by jlqzzz** [facebookresearch/xcit#5]
Thank you for publishing the great work!

I want to know how to visualize the attention map?

Is there a corresponding visualization code?

**Comment by aelnouby** [comment]
I will work on adding a visualization code. In the meantime, you can use the DINO [video_generation.py](https://github.com/facebookresearch/dino/blob/main/video_generation.py) code which we have adapted to generate the attention map videos in the README.

**Comment by cyrilzakka** [comment]
@aelnouby would you mind highlighting the changes that need to be made to XCiT to be able to use [video_generation.py](https://github.com/facebookresearch/dino/blob/main/video_generation.py)? So far, i've noticed that `prepare_tokens(self, x)` and `get_last_selfattention(self, x)` need to be added. Anything else?

**Comment by mckunkel** [comment]
Why is this closed? There seems to be no resolution nor help on this?

**Comment by alexioana** [comment]
any updates? or plans to get the `get_last_selfattention(self, x)` method in the XCiT class?
or an alternative?

the issue is definitely not resolved.
