### ISSUE TITLE
ERROR in requirements.txt

### ISSUE THREAD

**Issue by sahilkhose** [facebookresearch/xcit#6]
Getting the following error while executing requirements.txt
```
ERROR: Could not find a version that satisfies the requirement timm==0.4.8 (from -r requirements.txt (line 3)) (from versions: 0.1.1, 0.1.2, 0.1.4, 0.1.6, 0.1.8, 0.1.10, 0.1.12, 0.1.14, 0.1.16, 0.1.18, 0.1.20, 0.1.22, 0.1.24, 0.1.26, 0.1.28, 0.1.30, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.5, 0.4.9)
ERROR: No matching distribution found for timm==0.4.8 (from -r requirements.txt (line 3))
```
I think we have to change the version from 0.4.8 to 0.4.9

**Comment by woctezuma** [comment]
True. There is no v0.4.8 on PyPI: https://pypi.org/project/timm/#history

**Comment by aelnouby** [comment]
Thanks for spotting this problem, updated the version to 0.4.9 here (https://github.com/facebookresearch/xcit/commit/17dfb6e44c1de6062fc7770110f283f1c20fcf2f)
