### ISSUE TITLE
ImageNet-22K Models?

### ISSUE THREAD

**Issue by ErenBalatkan** [facebookresearch/xcit#8]
Greetings,

I would like first thank you for sharing the code of this amazing research.

When looking onto other competitive backbone models, such as Swin-Transformers, I see that their best results are coming from pretraiend ImageNet 22K models. Would it be possible for you guys to also release pre-trained 22K models? It would allow model to reach even higher results and possibly outperform Swin-L model that currently achieves 87.3 T1.

**Comment by aelnouby** [comment]
Thanks for your interest and question. We have plans for pre-training using IN-22k, hopefully if we can manage to do this successfully we will share the model weights on this repo.
